version: '3'

services:
  api:
    container_name: model_api
    restart: always
    build: ./api
    volumes: ['./api:/app']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "80"
    ports:
      - "80:80"

networks:
  apinetwork: